MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = '3'

__short_version__ = "{}.{}".format(MAJOR_VERSION, MINOR_VERSION)
__version__ = "{}.{}".format(__short_version__, PATCH_VERSION)


REQUIRED_PYTHON_VER = (3, 6, 0)

# ALARMS
POLICE_CAR_1 = 0
POLICE_CAR_2 = 1
ACIDENT = 2
GHOST = 4
SNIPER_RIFLE = 5
BATTLE = 6
AIR_RAID = 7
BARK = 8

# DOORBELLS
DOORBELL = 10
KNOCK_AT_A_DOOR = 11
AMUSE = 12
ALARM_CLOCK = 13

# ALRAM CLOCKS
MIMIX = 20
ENTHUSIASTIC = 21
GUITAR_CLASSIC = 22
ICE_WORLD_PIANO = 23
LEISURE_TIME = 24
CHILD_HOOD = 25
MORNING_STREAM_LIET = 26
MUSIC_BOX = 27
ORANGE = 28
THINKER = 29
